#!/bin/bash

# Azure Service Principal Creation Script
# This script creates a service principal with Contributor access for Terraform

set -e

# Configuration
SP_NAME="${SP_NAME:-aks-terraform-sp}"
ROLE="${ROLE:-Contributor}"

# Colors for output
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

echo -e "${GREEN}========================================${NC}"
echo -e "${GREEN}Azure Service Principal Creator${NC}"
echo -e "${GREEN}========================================${NC}"
echo ""

# Check if Azure CLI is installed
if ! command -v az &> /dev/null; then
    echo -e "${RED}Error: Azure CLI is not installed${NC}"
    echo "Install from: https://docs.microsoft.com/en-us/cli/azure/install-azure-cli"
    exit 1
fi

# Check if logged in
echo "Checking Azure login status..."
if ! az account show &> /dev/null; then
    echo -e "${RED}Error: Not logged in to Azure${NC}"
    echo "Please run: az login"
    exit 1
fi

# Get subscription details
SUBSCRIPTION_ID=$(az account show --query id -o tsv)
SUBSCRIPTION_NAME=$(az account show --query name -o tsv)

echo -e "${GREEN}✓${NC} Logged in to Azure"
echo "Subscription: $SUBSCRIPTION_NAME"
echo "Subscription ID: $SUBSCRIPTION_ID"
echo ""

# Create service principal
echo "Creating service principal: $SP_NAME"
echo "Role: $ROLE"
echo "Scope: /subscriptions/$SUBSCRIPTION_ID"
echo ""

SP_OUTPUT=$(az ad sp create-for-rbac \
  --name "$SP_NAME" \
  --role "$ROLE" \
  --scopes /subscriptions/$SUBSCRIPTION_ID \
  --output json)

if [ $? -ne 0 ]; then
    echo -e "${RED}Error: Failed to create service principal${NC}"
    exit 1
fi

# Extract credentials
CLIENT_ID=$(echo $SP_OUTPUT | jq -r '.appId')
CLIENT_SECRET=$(echo $SP_OUTPUT | jq -r '.password')
TENANT_ID=$(echo $SP_OUTPUT | jq -r '.tenant')

echo "Extracted credentials:"
echo "CLIENT_ID: $CLIENT_ID"
echo "CLIENT_SECRET: $CLIENT_SECRET"
echo "TENANT_ID: $TENANT_ID"
echo ""

# Display results
echo ""
echo -e "${GREEN}============================================${NC}"
echo -e "${GREEN}✓ Service Principal Created Successfully!${NC}"
echo -e "${GREEN}============================================${NC}"
echo ""
echo "Service Principal Name: $SP_NAME"
echo "Client ID (App ID):     $CLIENT_ID"
echo "Client Secret:          $CLIENT_SECRET"
echo "Tenant ID:              $TENANT_ID"
echo "Subscription ID:        $SUBSCRIPTION_ID"
echo "Role:                   $ROLE"
echo ""

# Create terraform.tfvars file
TFVARS_FILE="terraform.tfvars"
if [ -f "$TFVARS_FILE" ]; then
    echo -e "${YELLOW}⚠️  Warning: $TFVARS_FILE already exists${NC}"
    TFVARS_FILE="terraform.tfvars.generated"
    echo "Creating: $TFVARS_FILE instead"
    echo ""
fi

cat > "$TFVARS_FILE" << EOF
# Auto-generated by create-az-sp.sh on $(date)
# Service Principal: $SP_NAME

client_id       = "$CLIENT_ID"
client_secret   = "$CLIENT_SECRET"
location        = "westeurope"
subscription_id = "$SUBSCRIPTION_ID"

# Optional: Uncomment and modify as needed
# resource_group_name = "my-aks-rg"
# create_resource_group = true
# key_vault_firewall_bypass_ip_cidr = "YOUR_IP/32"
EOF

echo -e "${GREEN}✓${NC} Created $TFVARS_FILE"
echo ""

# Display next steps
echo -e "${GREEN}============================================${NC}"
echo -e "${GREEN}Next Steps:${NC}"
echo -e "${GREEN}============================================${NC}"
echo ""
echo "1. Review the generated $TFVARS_FILE file"
echo "2. Run: terraform init"
echo "3. Run: terraform plan"
echo "4. Run: terraform apply"
echo ""
echo -e "${YELLOW}⚠️  IMPORTANT SECURITY NOTES:${NC}"
echo "• Save the Client Secret securely - it cannot be retrieved later"
echo "• Add terraform.tfvars to .gitignore to avoid committing secrets"
echo "• Consider using Azure Key Vault or environment variables for secrets"
echo "• To delete this SP later, run: az ad sp delete --id $CLIENT_ID"
echo ""

echo ""
echo -e "${GREEN}Done!${NC}"
echo ""
